name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all

  test-wasm:
    name: Test (wasm32)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm wasm-bindgen-cli
      - uses: Swatinem/rust-cache@v2
      - run: cargo test -p typewire --target wasm32-unknown-unknown

  e2e:
    name: End-to-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm wasm-bindgen-cli
      - uses: Swatinem/rust-cache@v2
      - run: cargo build -p todo-app --target wasm32-unknown-unknown --release
      - name: TypeScript snapshot
        run: |
          cargo run -p typewire --features cli -- target/wasm32-unknown-unknown/release/todo_app.wasm --no-strip -o examples/todo-app/types.gen.d.ts
          diff examples/todo-app/types.d.ts examples/todo-app/types.gen.d.ts
      - name: JS runtime test
        run: |
          wasm-bindgen target/wasm32-unknown-unknown/release/todo_app.wasm --out-dir examples/todo-app/pkg --target nodejs --no-typescript
          node examples/todo-app/test.mjs

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo xtask lint

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --no-deps --all
        env:
          RUSTDOCFLAGS: -D warnings

  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm rust-toolchain
      - uses: EmbarkStudios/cargo-deny-action@v2
